// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eogpablvlwejutlmiyir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvZ3BhYmx2bHdlanV0bG1peWlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMDIzNDAsImV4cCI6MjA2NDU3ODM0MH0.PmwdSmbuzUp-OBqM-oCS9SAU5RKJCf0mmoSueFYaHy0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);